import type { Metadata } from "next";
import { DesignSystemProvider } from "@repo/design-system";
import { fonts } from "@repo/design-system/lib/fonts";
import { cn } from "@repo/design-system/lib/utils";

import "@repo/design-system/styles/globals.css";

import Header from "./components/header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={cn(fonts, "scroll-smooth")} lang="en">
      <body>
        <DesignSystemProvider>
          <Header />
          {children}
        </DesignSystemProvider>
      </body>
    </html>
  );
}
